version: "3.3"
services:
  # riskjournal-cli:
  #   # build: git@github.com:lenaschimmel/riskjournal-cli.git
  #   # while developing, you can use this line instead:
  #   build: ../riskjournal-cli
  #   image: riskjournal-cli:local

  riskjournal-server:
    # build: git@github.com:lenaschimmel/riskjournal-server.git
    # while developing, you can use this line instead:
    build: ../riskjournal-server
    image: riskjournal-server:local
    ports:
      - "26843:26843"
    volumes:
      - filevolume:/files

  covid-incidence-germany:
    # build: git@github.com:lenaschimmel/ covid-incidence-germany.git
    # while developing, you can use this line instead:
    build: ../covid-incidence-germany
    image:  covid-incidence-germany:local
    volumes:
      - filevolume:/files

volumes:
  filevolume: